[build]
  publish = "dist"
  command = "npm ci --production=false && npm run build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--production=false"
  CI = "false"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle Firebase auth callbacks
[[redirects]]
  from = "/__/auth/handler"
  to = "https://__REPLACE_WITH_YOUR_FIREBASE_AUTH_DOMAIN/__/auth/handler"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  
  # Update CSP to include all required Firebase domains
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-eval' 'unsafe-inline' https://apis.google.com https://www.gstatic.com https://www.google.com https://www.google-analytics.com https://*.firebaseio.com https://*.googleapis.com *.firebase.com *.firebaseapp.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    img-src 'self' data: blob: https://*.googleusercontent.com https://*.gstatic.com https://firebasestorage.googleapis.com https://storage.googleapis.com https://www.google.com https://www.google-analytics.com;
    font-src 'self' https://fonts.gstatic.com data:;
    connect-src 'self' https://*.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com https://*.firebase.com https://*.google-analytics.com https://*.google.com;
    frame-src 'self' https://*.firebaseapp.com https://*.google.com https://accounts.google.com https://www.google.com https://www.recaptcha.net;
    media-src 'self' data: blob:;
    object-src 'none';
    base-uri 'self';
    form-action 'self' https://*.firebaseapp.com https://*.google.com;
    frame-ancestors 'none';
  """.replace(/\s+/g, " ").trim()

# Cache settings for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML
[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

# Security headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
